### ISSUE TITLE
7.0.2 not working at all

### ISSUE THREAD

**Issue by Blysq** [dotcore64/gulp-i18next-conv#69]
Getting ```TypeError: i18next is not a function```

gulp version: 4.0.0
node version: 10.15.3

Happens only when installed with yarn.

**Comment by perrin4869** [comment]
@Blysq Hm... interesting. I don't have experience using yarn. Any clues what might be the cause?
Is the default export not being exported properly?

**Comment by Blysq** [comment]
@perrin4869 yarn produces no errors.

I tried to install it with npm and it produced the same error. Maybe it's not a problem with yarn.

Yarn produces no errors when installing it.

I can see the difference in files between version 7.0.1 tho. 
dist - doesn't exist
lib - exactly the same

Version 7.0.1 installs and works fine.

The difference in package.json between version 7.0.1 and 7.0.2 is:
```
{
  "name": "gulp-i18next-conv",
  "version": "7.0.2",
  "description": "Gulp plugin to convert gettext .po or .mo files to i18next compatible JSON",
  "main": "lib/index.js"
   ...
}
```
vs
```
{
  "name": "gulp-i18next-conv",
  "version": "7.0.1",
  "description": "Gulp plugin to convert gettext .po or .mo files to i18next compatible JSON",
  "main": "dist/index.js"
  ...
}
```

**Comment by perrin4869** [comment]
@Blysq please check if `8.0.1` fixes your issue!! Please reopen if it is still there
